version: "3.8"

services:

  backend:
    build: ./backend
    container_name: mir_server
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - kibana
  elasticsearch:
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.14.2
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver: local
